### ISSUE TITLE
What do set as Database_url= in .env file

### ISSUE THREAD

**Issue by JasonMKY** [AntonioErdeljac/next13-ai-companion#7]
What should I set the DATABASE_URL= in the .env file? New to coding.

**Comment by ramene** [comment]
Your MYSQL database string from Planetscale; i.e.

`DATABASE_URL='mysql://username:password@aws.connect.psdb.cloud/companion?sslaccept=strict'`

**Comment by JasonMKY** [comment]
> Your MYSQL database string from Planetscale; i.e.
> 
> `DATABASE_URL='mysql://username:password@aws.connect.psdb.cloud/companion?sslaccept=strict'`

What should I choose for the language or framework or does it not matter?
![image](https://github.com/AntonioErdeljac/next13-ai-companion/assets/104327713/c95426d2-e1c3-4745-92e4-e2ef1c258806)

**Comment by ramene** [comment]
You're using Prisma.
